version: 2
updates:
  - package-ecosystem: "github-actions" # zizmor: ignore[dependabot-cooldown]
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: "uv" # zizmor: ignore[dependabot-cooldown]
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      uv-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: "docker-compose" # zizmor: ignore[dependabot-cooldown]
    directories:
      - "/docker/reference"
      - "/docker/reference/*"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      docker-compose:
        patterns:
          - "*"
        group-by: "dependency-name"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: "docker" # zizmor: ignore[dependabot-cooldown]
    directory: "/docker/reference/token-exchange"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
