"""Shared internal helpers for controller classes."""

from __future__ import annotations

import logging
from collections.abc import Awaitable, Callable
from typing import TYPE_CHECKING, Any, Protocol

from litestar import Request
from litestar.exceptions import ClientException

import litestar_auth._account_state as _shared_account_state
from litestar_auth.controllers._error_responses import (
    AccountStateFailureCallback,
    DomainErrorMap,
    _create_error_response,
    _domain_error_public_detail,
    _map_domain_exceptions,
    _resolve_domain_error_response,
)
from litestar_auth.exceptions import ErrorCode, InactiveUserError, UnverifiedUserError

logger = logging.getLogger(__name__)
_ACCOUNT_STATE_ERROR_TYPES = _shared_account_state.AccountStateErrorTypes(
    inactive_error=InactiveUserError,
    unverified_error=UnverifiedUserError,
)

if TYPE_CHECKING:
    from litestar_auth.ratelimit import EndpointRateLimit

_LITESTAR_AUTH_ROUTE_HANDLER_ATTR = "__litestar_auth_route_handler__"

type RequestHandler = Callable[[Request[Any, Any, Any]], Awaitable[None]]


class AccountStateValidatorProvider[UP](Protocol):
    """Explicit manager seam for controller account-state validation."""

    def require_account_state(self, user: UP, *, require_verified: bool = False) -> None:
        """Validate active and optionally verified account state."""


_resolve_account_state_validator = _shared_account_state.resolve_account_state_validator


def _require_account_state_from_attributes(
    user: object,
    *,
    require_verified: bool,
) -> None:
    """Apply controller account-state validation from user attributes only."""
    _shared_account_state.require_account_state(
        user,
        require_verified=require_verified,
        user_manager=None,
        error_types=_ACCOUNT_STATE_ERROR_TYPES,
    )


def _mark_litestar_auth_route_handler[RouteHandlerT](route_handler: RouteHandlerT) -> RouteHandlerT:
    """Mark a generated controller/route handler as owned by litestar-auth.

    Returns:
        The same route handler, marked for auth-specific exception wiring.
    """
    setattr(route_handler, _LITESTAR_AUTH_ROUTE_HANDLER_ATTR, True)
    return route_handler


def _is_litestar_auth_route_handler(route_handler: object) -> bool:
    """Return whether a controller/route handler was generated by litestar-auth."""
    return bool(getattr(route_handler, _LITESTAR_AUTH_ROUTE_HANDLER_ATTR, False))


from litestar_auth.controllers._request_body import (  # noqa: E402
    _HTTP_BAD_REQUEST,
    ErrorCallback,
    RequestBodyErrorConfig,
    RequestBodyRouteHandler,
    _configure_request_body_handler,
    _create_request_body_exception_handlers,
    _decode_request_body,
    _set_data_parameter_annotation,
)
from litestar_auth.controllers._user_schema import _require_msgspec_struct, _to_user_schema  # noqa: E402

__all__ = (
    "_HTTP_BAD_REQUEST",
    "AccountStateFailureCallback",
    "AccountStateValidatorProvider",
    "DomainErrorMap",
    "ErrorCallback",
    "ErrorCode",
    "RequestBodyErrorConfig",
    "RequestBodyRouteHandler",
    "RequestHandler",
    "_build_controller_name",
    "_configure_request_body_handler",
    "_create_before_request_handler",
    "_create_error_response",
    "_create_rate_limit_handlers",
    "_create_request_body_exception_handlers",
    "_decode_request_body",
    "_domain_error_public_detail",
    "_is_litestar_auth_route_handler",
    "_map_domain_exceptions",
    "_mark_litestar_auth_route_handler",
    "_require_account_state",
    "_require_account_state_from_attributes",
    "_require_msgspec_struct",
    "_resolve_account_state_validator",
    "_resolve_domain_error_response",
    "_set_data_parameter_annotation",
    "_to_user_schema",
)


def _build_controller_name(name: str) -> str:
    """Return a class-name-safe prefix derived from a backend or provider name.

    Returns:
        Title-cased alphanumeric name suitable for generated controller classes.
    """
    normalized_name = "".join(part.capitalize() for part in name.replace("_", "-").split("-") if part)
    return normalized_name or "Generated"


def _create_rate_limit_handlers(rate_limit: EndpointRateLimit | None) -> tuple[RequestHandler, RequestHandler]:
    """Return increment/reset request handlers for an optional rate limit."""

    async def increment(request: Request[Any, Any, Any]) -> None:
        if rate_limit is not None:
            await rate_limit.increment(request)

    async def reset(request: Request[Any, Any, Any]) -> None:
        if rate_limit is not None:
            await rate_limit.reset(request)

    return increment, reset


def _create_before_request_handler(rate_limit: EndpointRateLimit | None) -> RequestHandler | None:
    """Return a ``before_request`` handler for an optional rate limit."""
    if rate_limit is None:
        return None

    async def before_request(request: Request[Any, Any, Any]) -> None:
        if rate_limit is not None:
            await rate_limit.before_request(request)

    return before_request


async def _require_account_state[UP](
    user: UP,
    *,
    require_verified: bool = False,
    user_manager: AccountStateValidatorProvider[UP] | None = None,
    on_failure: AccountStateFailureCallback | None = None,
) -> None:
    """Validate controller account-state policy and map failures to client errors.

    Args:
        user: User object to validate.
        require_verified: When ``True``, also reject unverified users.
        user_manager: Optional manager exposing ``require_account_state()``.
        on_failure: Optional async callback invoked before raising a client error.

    Raises:
        ClientException: If the account is inactive or unverified.
    """
    try:
        _shared_account_state.require_account_state_with_client_error(
            user,
            require_verified=require_verified,
            user_manager=user_manager,
            error_types=_ACCOUNT_STATE_ERROR_TYPES,
        )
    except ClientException:
        if on_failure is not None:
            await on_failure()
        raise
