"""Canonical plugin feature registry and feature configuration contracts."""

from __future__ import annotations

from litestar_auth._plugin.features.registry import (
    DATABASE_TOKEN_FEATURE,
    DEFAULT_DATABASE_TOKEN_BACKEND_NAME,
    DEFAULT_DATABASE_TOKEN_BYTES,
    DEFAULT_DATABASE_TOKEN_MAX_AGE,
    DEFAULT_DATABASE_TOKEN_REFRESH_MAX_AGE,
    DEFAULT_TOTP_STEPUP_TTL_SECONDS,
    FEATURE_DEFAULTS,
    OAUTH_FEATURE,
    ORGANIZATION_FEATURE,
    TOTP_FEATURE,
    TOTP_STEPUP_POLICY_ENDPOINTS,
    DatabaseTokenAuthConfig,
    FeatureConfigSnapshot,
    FeatureDefaults,
    FeatureKey,
    FeatureRegistry,
    OAuthConfig,
    OrganizationConfig,
    OrganizationRolePrecedence,
    OrganizationStoreFactory,
    ResolvedFeatureDefaults,
    StartupBackendInventory,
    StartupBackendTemplate,
    TotpConfig,
    TotpStepUpPolicyMode,
    resolve_feature_defaults,
    resolve_feature_registry,
)

__all__ = (
    "DATABASE_TOKEN_FEATURE",
    "DEFAULT_DATABASE_TOKEN_BACKEND_NAME",
    "DEFAULT_DATABASE_TOKEN_BYTES",
    "DEFAULT_DATABASE_TOKEN_MAX_AGE",
    "DEFAULT_DATABASE_TOKEN_REFRESH_MAX_AGE",
    "DEFAULT_TOTP_STEPUP_TTL_SECONDS",
    "FEATURE_DEFAULTS",
    "OAUTH_FEATURE",
    "ORGANIZATION_FEATURE",
    "TOTP_FEATURE",
    "TOTP_STEPUP_POLICY_ENDPOINTS",
    "DatabaseTokenAuthConfig",
    "FeatureConfigSnapshot",
    "FeatureDefaults",
    "FeatureKey",
    "FeatureRegistry",
    "OAuthConfig",
    "OrganizationConfig",
    "OrganizationRolePrecedence",
    "OrganizationStoreFactory",
    "ResolvedFeatureDefaults",
    "StartupBackendInventory",
    "StartupBackendTemplate",
    "TotpConfig",
    "TotpStepUpPolicyMode",
    "resolve_feature_defaults",
    "resolve_feature_registry",
)
