"""Framework-neutral principal authentication contracts."""

from authweave_core.coordinator import AuthenticationCoordinator, RequestAuthenticationProvider
from authweave_core.models import (
    Authenticated,
    AuthenticationContext,
    AuthenticationDecision,
    AuthenticationEvidence,
    AuthenticationRuntime,
    AuthorizationValue,
    CredentialMatch,
    EvidenceValue,
    FailureCode,
    Invalid,
    InvariantFailure,
    NotApplicable,
    PrincipalRef,
    RequestView,
    RouteProviderPolicy,
    SpiffePeerEvidence,
    TlsPeerEvidence,
    Unavailable,
    freeze_authorization_details,
)
from authweave_core.observability import (
    SecurityObservation,
    SecurityObservationContext,
    SecurityObserver,
    SecurityOperation,
    SecurityOutcome,
    TraceCorrelation,
    ambient_trace_correlation,
    current_trace_correlation,
    observe_security,
)
from authweave_core.replay import (
    InMemoryReplayStore,
    ReplayOutcome,
    ReplayStore,
    validate_replay_key,
)

__version__ = "7.1.2"

__all__ = (
    "Authenticated",
    "AuthenticationContext",
    "AuthenticationCoordinator",
    "AuthenticationDecision",
    "AuthenticationEvidence",
    "AuthenticationRuntime",
    "AuthorizationValue",
    "CredentialMatch",
    "EvidenceValue",
    "FailureCode",
    "InMemoryReplayStore",
    "Invalid",
    "InvariantFailure",
    "NotApplicable",
    "PrincipalRef",
    "ReplayOutcome",
    "ReplayStore",
    "RequestAuthenticationProvider",
    "RequestView",
    "RouteProviderPolicy",
    "SecurityObservation",
    "SecurityObservationContext",
    "SecurityObserver",
    "SecurityOperation",
    "SecurityOutcome",
    "SpiffePeerEvidence",
    "TlsPeerEvidence",
    "TraceCorrelation",
    "Unavailable",
    "__version__",
    "ambient_trace_correlation",
    "current_trace_correlation",
    "freeze_authorization_details",
    "observe_security",
    "validate_replay_key",
)
